### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/untd-site#34]
## Objective
Design a favicon and add to the site

## Tasks
- [x] Design favicon (Sasha)
- [x] Client approval of favicon 
- [x] Implement favicon (Connor)

**Comment by laurendoone** [comment]
@touchRED figma has a few draft favicons. when sasha is back from vacation he can let us know which is final

**Comment by ekmason** [comment]
Favicon designed and signed off by the client, ready for implementation @touchRED! 
Figma can be found [here](https://www.figma.com/file/Xxu6JB55X7j77cGahUmqWO/UNTD-Mockups-and-Wireframes?node-id=631%3A0)
