### ISSUE TITLE
Update About Page with Designs

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/untd-site#70]
## Objective
Apply styles in updated About Page mockup found [here](https://www.figma.com/file/Xxu6JB55X7j77cGahUmqWO/UNTD-Mockups-and-Wireframes?node-id=1292%3A1)

## Tasks
- [ ] Add/update section on the Center for Socioeconomic Mobility for Learning 
- [ ] Add "Click here to Learn More About the Center" link 

## Acceptance Criteria
- [ ] Section on the Center matches mockups
- [ ] User can click link to learn more about the Center and jump to corresponding section in the page
