### ISSUE TITLE
Update Homepage with Designs

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/untd-site#72]
## Objective
Update the homepage to match Sasha's [design updates](https://www.figma.com/file/Xxu6JB55X7j77cGahUmqWO/UNTD-Mockups-and-Wireframes?node-id=1211%3A0)

From Sasha: 
> For the homepage the links for the ‘What is socioeconomic mobility?’ section and buttons further down can be updated to make them more visible and consistent with the rest of the site.

## Tasks
- [x] Update `View Pathways` button 
- [x] Ensure homepage matches mockups
- [ ] Boost text size (desktop only)
